name: Test Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'
          cache: 'npm'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: Generate Types (Develop)
        if: github.base_ref != 'master'
        run: |
          npm run gen:clean \
          && npm run gen:type

      - name: Generate Types (production)
        if: github.base_ref == 'master'
        run: |
          npm run gen:clean \
          && npm run gen:type:prod

      - name: Lint
        run: |
          npm run lint \
          && npm run format:check

      - name: Build
        run: cp .env.dev .env && npm run build

      - name: Upload Assets to R2
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.RCLONE_CONFIG_R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_CONFIG_R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.RCLONE_CONFIG_R2_ENDPOINT }}
        with:
          args: sync .next r2:matters-assets-next-develop/.next -P
