name: Test

on:
  push:
    branches-ignore:
      - develop
      - stage
env:
  MATTERS_TESTING_ACCOUNT_EMAIL: ${{ secrets.MATTERS_TESTING_ACCOUNT_EMAIL }}
  MATTERS_TESTING_ACCOUNT_PASSWORD: ${{ secrets.MATTERS_TESTING_ACCOUNT_PASSWORD }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'
          cache: 'npm'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: Generate Types (Develop)
        if: github.base_ref != 'master'
        run: |
          npm run gen:clean \
          && npm run gen:type

      - name: Generate Types (production)
        if: github.base_ref == 'master'
        run: |
          npm run gen:clean \
          && npm run gen:type:prod

      - name: Lint
        run: |
          npm run lint \
          && npm run format:check

      - name: Build
        run: cp .env.dev .env && npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: MATTERS_TESTING_ACCOUNT_EMAIL=${{ secrets.MATTERS_TESTING_ACCOUNT_EMAIL }} MATTERS_TESTING_ACCOUNT_PASSWORD=${{ secrets.MATTERS_TESTING_ACCOUNT_PASSWORD }} npx playwright test

      - name: Output Playwright tests
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
